# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vending_machine.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1021, 783)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 1001, 380))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.items_gridlayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.items_gridlayout.setContentsMargins(10, 10, 10, 10)
        self.items_gridlayout.setSpacing(10)
        self.items_gridlayout.setObjectName("items_gridlayout")
        self.item_4_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.item_4_button.setFont(font)
        self.item_4_button.setObjectName("item_4_button")
        self.items_gridlayout.addWidget(self.item_4_button, 4, 4, 1, 1)
        self.item_1_picture = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.item_1_picture.setText("")
        self.item_1_picture.setPixmap(QtGui.QPixmap("assets/images/KoKaCola.jpeg"))
        self.item_1_picture.setOpenExternalLinks(False)
        self.item_1_picture.setObjectName("item_1_picture")
        self.items_gridlayout.addWidget(self.item_1_picture, 1, 0, 1, 1)
        self.item_1_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.item_1_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.item_1_label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.item_1_label.setFont(font)
        self.item_1_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.item_1_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.item_1_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.item_1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.item_1_label.setObjectName("item_1_label")
        self.items_gridlayout.addWidget(self.item_1_label, 2, 0, 1, 1)
        self.item_4_picture = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.item_4_picture.setText("")
        self.item_4_picture.setPixmap(QtGui.QPixmap("assets/images/Water.jpeg"))
        self.item_4_picture.setOpenExternalLinks(False)
        self.item_4_picture.setObjectName("item_4_picture")
        self.items_gridlayout.addWidget(self.item_4_picture, 1, 4, 1, 1)
        self.item_1_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.item_1_button.setFont(font)
        self.item_1_button.setObjectName("item_1_button")
        self.items_gridlayout.addWidget(self.item_1_button, 4, 0, 1, 1)
        self.item_2_picture = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.item_2_picture.setText("")
        self.item_2_picture.setPixmap(QtGui.QPixmap("assets/images/Pepchi.jpeg"))
        self.item_2_picture.setOpenExternalLinks(False)
        self.item_2_picture.setObjectName("item_2_picture")
        self.items_gridlayout.addWidget(self.item_2_picture, 1, 2, 1, 1)
        self.item_3_picture = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.item_3_picture.setText("")
        self.item_3_picture.setPixmap(QtGui.QPixmap("assets/images/Starblues.jpeg"))
        self.item_3_picture.setOpenExternalLinks(False)
        self.item_3_picture.setObjectName("item_3_picture")
        self.items_gridlayout.addWidget(self.item_3_picture, 1, 3, 1, 1)
        self.item_3_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.item_3_button.setFont(font)
        self.item_3_button.setObjectName("item_3_button")
        self.items_gridlayout.addWidget(self.item_3_button, 4, 3, 1, 1)
        self.item_2_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.item_2_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.item_2_label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.item_2_label.setFont(font)
        self.item_2_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.item_2_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.item_2_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.item_2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.item_2_label.setObjectName("item_2_label")
        self.items_gridlayout.addWidget(self.item_2_label, 2, 2, 1, 1)
        self.item_3_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.item_3_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.item_3_label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.item_3_label.setFont(font)
        self.item_3_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.item_3_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.item_3_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.item_3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.item_3_label.setObjectName("item_3_label")
        self.items_gridlayout.addWidget(self.item_3_label, 2, 3, 1, 1)
        self.item_4_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.item_4_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.item_4_label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.item_4_label.setFont(font)
        self.item_4_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.item_4_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.item_4_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.item_4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.item_4_label.setObjectName("item_4_label")
        self.items_gridlayout.addWidget(self.item_4_label, 2, 4, 1, 1)
        self.item_2_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.item_2_button.setFont(font)
        self.item_2_button.setObjectName("item_2_button")
        self.items_gridlayout.addWidget(self.item_2_button, 4, 2, 1, 1)
        self.input_cash_lcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.input_cash_lcd.setGeometry(QtCore.QRect(750, 670, 261, 61))
        self.input_cash_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_cash_lcd.setProperty("intValue", 150)
        self.input_cash_lcd.setObjectName("input_cash_lcd")
        self.input_cash_500won = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.input_cash_500won.setGeometry(QtCore.QRect(750, 520, 81, 81))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/images/100won.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.input_cash_500won.setIcon(icon)
        self.input_cash_500won.setIconSize(QtCore.QSize(100, 100))
        self.input_cash_500won.setObjectName("input_cash_500won")
        self.output_item_box = QtWidgets.QLabel(self.centralwidget)
        self.output_item_box.setGeometry(QtCore.QRect(10, 520, 251, 231))
        self.output_item_box.setText("")
        self.output_item_box.setPixmap(QtGui.QPixmap("assets/images/output_box_item.jpeg"))
        self.output_item_box.setOpenExternalLinks(False)
        self.output_item_box.setObjectName("output_item_box")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(10, 10, 1001, 61))
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.title_label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.title_label.setLineWidth(1)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.output_item_label = QtWidgets.QLabel(self.centralwidget)
        self.output_item_label.setGeometry(QtCore.QRect(10, 460, 251, 61))
        self.output_item_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.output_item_label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.output_item_label.setFont(font)
        self.output_item_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output_item_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_item_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.output_item_label.setLineWidth(1)
        self.output_item_label.setAlignment(QtCore.Qt.AlignCenter)
        self.output_item_label.setObjectName("output_item_label")
        self.output_change_label = QtWidgets.QLabel(self.centralwidget)
        self.output_change_label.setGeometry(QtCore.QRect(270, 460, 241, 61))
        self.output_change_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.output_change_label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.output_change_label.setFont(font)
        self.output_change_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output_change_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_change_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.output_change_label.setLineWidth(1)
        self.output_change_label.setAlignment(QtCore.Qt.AlignCenter)
        self.output_change_label.setObjectName("output_change_label")
        self.output_change_box = QtWidgets.QLabel(self.centralwidget)
        self.output_change_box.setGeometry(QtCore.QRect(270, 520, 241, 231))
        self.output_change_box.setText("")
        self.output_change_box.setPixmap(QtGui.QPixmap("assets/images/output_box_change.jpeg"))
        self.output_change_box.setOpenExternalLinks(False)
        self.output_change_box.setObjectName("output_change_box")
        self.input_cash_label = QtWidgets.QLabel(self.centralwidget)
        self.input_cash_label.setGeometry(QtCore.QRect(750, 610, 261, 61))
        self.input_cash_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.input_cash_label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_cash_label.setFont(font)
        self.input_cash_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_cash_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_cash_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.input_cash_label.setLineWidth(1)
        self.input_cash_label.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cash_label.setObjectName("input_cash_label")
        self.input_cash_selection = QtWidgets.QLabel(self.centralwidget)
        self.input_cash_selection.setGeometry(QtCore.QRect(750, 460, 261, 61))
        self.input_cash_selection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.input_cash_selection.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.input_cash_selection.setFont(font)
        self.input_cash_selection.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_cash_selection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_cash_selection.setFrameShadow(QtWidgets.QFrame.Plain)
        self.input_cash_selection.setLineWidth(1)
        self.input_cash_selection.setAlignment(QtCore.Qt.AlignCenter)
        self.input_cash_selection.setObjectName("input_cash_selection")
        self.input_cash_1000won = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.input_cash_1000won.setGeometry(QtCore.QRect(840, 520, 81, 81))
        self.input_cash_1000won.setIcon(icon)
        self.input_cash_1000won.setIconSize(QtCore.QSize(100, 100))
        self.input_cash_1000won.setObjectName("input_cash_1000won")
        self.input_cash_100won = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.input_cash_100won.setGeometry(QtCore.QRect(930, 520, 81, 81))
        self.input_cash_100won.setIcon(icon)
        self.input_cash_100won.setIconSize(QtCore.QSize(100, 100))
        self.input_cash_100won.setObjectName("input_cash_100won")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionABC = QtWidgets.QAction(MainWindow)
        self.actionABC.setObjectName("actionABC")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vending_Machine"))
        self.item_4_button.setText(_translate("MainWindow", "O"))
        self.item_1_label.setText(_translate("MainWindow", "KoKaCola"))
        self.item_1_button.setText(_translate("MainWindow", "O"))
        self.item_3_button.setText(_translate("MainWindow", "O"))
        self.item_2_label.setText(_translate("MainWindow", "Pepchi"))
        self.item_3_label.setText(_translate("MainWindow", "Starblues Latte"))
        self.item_4_label.setText(_translate("MainWindow", "Water"))
        self.item_2_button.setText(_translate("MainWindow", "O"))
        self.input_cash_500won.setText(_translate("MainWindow", "cash"))
        self.title_label.setText(_translate("MainWindow", "Vending Machine for Beberages"))
        self.output_item_label.setText(_translate("MainWindow", "상품 배출구"))
        self.output_change_label.setText(_translate("MainWindow", "잔돈 배출구"))
        self.input_cash_label.setText(_translate("MainWindow", "투입금액"))
        self.input_cash_selection.setText(_translate("MainWindow", "동전 선택"))
        self.input_cash_1000won.setText(_translate("MainWindow", "cash"))
        self.input_cash_100won.setText(_translate("MainWindow", "cash"))
        self.actionABC.setText(_translate("MainWindow", "ABC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

