# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vending_machine.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 714)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 60, 1001, 341))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 4, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/pictures/coursework/homework1_NA/vending_machine/assets/images/KoKaCola.jpeg"))
        self.label_9.setOpenExternalLinks(False)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setBaseSize(QtCore.QSize(0, 0))
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/pictures/coursework/homework1_NA/vending_machine/assets/images/Water.jpeg"))
        self.label_13.setOpenExternalLinks(False)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 4, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/pictures/coursework/homework1_NA/vending_machine/assets/images/Pepchi.jpeg"))
        self.label_11.setOpenExternalLinks(False)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/pictures/coursework/homework1_NA/vending_machine/assets/images/Starblues.jpeg"))
        self.label_14.setOpenExternalLinks(False)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 1, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 4, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_15.setBaseSize(QtCore.QSize(0, 0))
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_16.setBaseSize(QtCore.QSize(0, 0))
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_17.setBaseSize(QtCore.QSize(0, 0))
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 4, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 4, 2, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(740, 610, 261, 61))
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdNumber.setProperty("intValue", 150)
        self.lcdNumber.setObjectName("lcdNumber")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(740, 460, 81, 81))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/images/100won.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon)
        self.commandLinkButton.setIconSize(QtCore.QSize(100, 100))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(0, 460, 251, 231))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/pictures/coursework/homework1_NA/vending_machine/assets/images/KoKaCola.jpeg"))
        self.label_12.setOpenExternalLinks(False)
        self.label_12.setObjectName("label_12")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(0, 0, 1001, 61))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_18.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_18.setLineWidth(1)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(0, 400, 251, 61))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_19.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_19.setLineWidth(1)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(260, 400, 241, 61))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_20.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_20.setLineWidth(1)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(260, 460, 241, 231))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(":/pictures/coursework/homework1_NA/vending_machine/assets/images/KoKaCola.jpeg"))
        self.label_21.setOpenExternalLinks(False)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(740, 550, 261, 61))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_22.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_22.setLineWidth(1)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(740, 400, 261, 61))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_23.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_23.setLineWidth(1)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.commandLinkButton_4 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_4.setGeometry(QtCore.QRect(830, 460, 81, 81))
        self.commandLinkButton_4.setIcon(icon)
        self.commandLinkButton_4.setIconSize(QtCore.QSize(100, 100))
        self.commandLinkButton_4.setObjectName("commandLinkButton_4")
        self.commandLinkButton_5 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_5.setGeometry(QtCore.QRect(920, 460, 81, 81))
        self.commandLinkButton_5.setIcon(icon)
        self.commandLinkButton_5.setIconSize(QtCore.QSize(100, 100))
        self.commandLinkButton_5.setObjectName("commandLinkButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionABC = QtWidgets.QAction(MainWindow)
        self.actionABC.setObjectName("actionABC")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vending_Machine"))
        self.pushButton_5.setText(_translate("MainWindow", "O"))
        self.label_10.setText(_translate("MainWindow", "KoKaCola"))
        self.pushButton_6.setText(_translate("MainWindow", "O"))
        self.pushButton_8.setText(_translate("MainWindow", "O"))
        self.label_15.setText(_translate("MainWindow", "Pepchi"))
        self.label_16.setText(_translate("MainWindow", "Starblues Latte"))
        self.label_17.setText(_translate("MainWindow", "Water"))
        self.pushButton_7.setText(_translate("MainWindow", "O"))
        self.commandLinkButton.setText(_translate("MainWindow", "cash"))
        self.label_18.setText(_translate("MainWindow", "Vending Machine for Beberages"))
        self.label_19.setText(_translate("MainWindow", "Hole1"))
        self.label_20.setText(_translate("MainWindow", "Hole2"))
        self.label_22.setText(_translate("MainWindow", "투입금액"))
        self.label_23.setText(_translate("MainWindow", "동전 선택"))
        self.commandLinkButton_4.setText(_translate("MainWindow", "cash"))
        self.commandLinkButton_5.setText(_translate("MainWindow", "cash"))
        self.actionABC.setText(_translate("MainWindow", "ABC"))

import test_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

